{% materialization table, adapter = 'iceberg', supported_languages=['sql', 'python'] %}
  {%- set language = model['language'] -%}
  {%- set identifier = model['alias'] -%}
  {%- set grant_config = config.get('grants') -%}

  {%- set old_relation = adapter.get_relation(database=database, schema=schema, identifier=identifier) -%}
  {%- set target_relation = api.Relation.create(identifier=identifier,
                                                schema=schema,
                                                database=database,
                                                type='table') -%}

  {{ run_hooks(pre_hooks) }}

  -- setup: if the target relation already exists, drop it
  -- in case if the existing and future table is delta or iceberg, we want to do a
  -- create or replace table instead of dropping, so we don't have the table unavailable
  {% if old_relation is not none %}
    {% set is_delta = (old_relation.is_delta and config.get('file_format', validator=validation.any[basestring]) == 'delta') %}
    {% set is_iceberg = (old_relation.is_iceberg and config.get('file_format', validator=validation.any[basestring]) == 'iceberg') %}
    {% set old_relation_type = old_relation.type %}
  {% else %}
    {% set is_delta = false %}
    {% set is_iceberg = false %}
    {% set old_relation_type = target_relation.type %}
  {% endif %}

  {% if not is_delta and not is_iceberg %}
    {% set existing_relation = target_relation %}
    {{ adapter.drop_relation(existing_relation.incorporate(type=old_relation_type)) }}
  {% endif %}

  -- build model
  {%- call statement('main', language=language) -%}
    {{ create_table_as(False, target_relation, compiled_code, language) }}
  {%- endcall -%}

  {% set should_revoke = should_revoke(old_relation, full_refresh_mode=True) %}
  {% do apply_grants(target_relation, grant_config, should_revoke) %}

  {% do persist_docs(target_relation, model) %}

  {% do persist_constraints(target_relation, model) %}

  {{ run_hooks(post_hooks) }}

  {{ return({'relations': [target_relation]})}}

{% endmaterialization %}


{% macro py_write_table(compiled_code, target_relation) %}
{{ compiled_code }}
# --- Autogenerated dbt materialization code (Kubernetes / PyIceberg mode) --- #
import os as _os
import polars as _pl
from pyiceberg.catalog.rest import RestCatalog as _RestCatalog


def _make_dbt_context():
    _props = {
        "uri": _os.environ["ICEBERG_REST_URI"],
        "warehouse": _os.environ["ICEBERG_WAREHOUSE"],
    }
    _token = _os.environ.get("ICEBERG_TOKEN")
    if _token:
        _props["token"] = _token
    _catalog = _RestCatalog("dbt_catalog", **_props)

    class _DbtContext:
        def ref(self, model_name):
            _schema = _os.environ["DBT_SCHEMA"]
            _tbl = _catalog.load_table(f"{_schema}.{model_name}")
            return _pl.from_arrow(_tbl.scan().to_arrow())

        def source(self, source_name, table_name):
            _tbl = _catalog.load_table(f"{source_name}.{table_name}")
            return _pl.from_arrow(_tbl.scan().to_arrow())

    return _DbtContext(), _catalog


_dbt_ctx, _iceberg_catalog = _make_dbt_context()

# session=None: Polars does not need a session object
_result_df = model(_dbt_ctx, None)

if not isinstance(_result_df, _pl.DataFrame):
    raise TypeError(
        f"model() must return a polars.DataFrame, got {type(_result_df).__name__}"
    )

# Write the result to the Iceberg REST catalog
_target_table = f"{_os.environ['DBT_SCHEMA']}.{_os.environ['DBT_IDENTIFIER']}"
_arrow_table = _result_df.to_arrow()

try:
    _iceberg_table = _iceberg_catalog.load_table(_target_table)
    _iceberg_table.overwrite(_arrow_table)
except Exception:
    import pyarrow as _pa
    _iceberg_catalog.create_table(_target_table, schema=_arrow_table.schema).overwrite(_arrow_table)

print(f"Written {len(_result_df)} rows to {_target_table}")
{%- endmacro -%}

{%macro py_script_comment()%}
# dbt Kubernetes / PyIceberg model interface:
# def model(dbt, session):
#     # dbt.ref("other_model") -> polars.DataFrame from Iceberg table
#     # dbt.source("source_name", "table_name") -> polars.DataFrame
#     # session is None (not needed for Polars)
#     import polars as pl
#     return pl.DataFrame({"col": [1, 2, 3]})
{%endmacro%}
